In [1]:
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.naive_bayes import MultinomialNB

In [3]:
imdb = pd.read_csv('imdb_master.csv', encoding = "ISO-8859-1", index_col = 0)

In [4]:
len(imdb)

100000

In [5]:
imdb.head()

   type                                             review label         file
0  test  Once again Mr. Costner has dragged out a movie...   neg      0_2.txt
1  test  This is an example of why the majority of acti...   neg  10000_4.txt
2  test  First of all I hate those moronic rappers, who...   neg  10001_1.txt
3  test  Not even the Beatles could write songs everyon...   neg  10002_3.txt
4  test  Brass pictures (movies is not a fitting word f...   neg  10003_3.txt

In [6]:
imdb.loc[67]['review']

"This film is on my list of worst movies ever made. The story is disconnected and it is difficult to understand what is going on or the reason for the characters' actions. All films need to have an inner logic, and this film just doesn't have it - the story doesn't make any sense. <br /><br />To see Faye Dunaway, Christopher Plummer and Diana Quick wasting their talents in this movie is a crime. Faye Dunaway is the lucky one, because she plays the victim and gets killed early in the film. On the other hand, Donald Sutherland must be an amazing actor because he manages to look good in spite of bad directing and bad writing; his performance is believable and he manages to stay in character in spite of everything. <br /><br />If Dame Agatha Christie were alive she would die laughing! The movie is that bad!"

In [7]:
imdb['type'].unique()

array(['test', 'train'], dtype=object)

In [8]:
imdb['label'].unique()

array(['neg', 'pos', 'unsup'], dtype=object)

In [9]:
imdb['type'] == 'train'

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
99970     True
99971     True
99972     True
99973     True
99974     True
99975     True
99976     True
99977     True
99978     True
99979     True
99980     True
99981     True
99982     True
99983     True
99984     True
99985     True
99986     True
99987     True
99988     True
99989     True
99990     True
99991     True
99992     True
99993     True
99994     True
99995     True
99996     True
99997     True
99998     True
99999     True
Name: type, Length: 100000, dtype: bool

In [10]:
imdb[imdb['type'] == 'train']

,type,review,label,file
25000,train,Story of a man who has unnatural feelings for ...,neg,0_3.txt
25001,train,Airport '77 starts as a brand new luxury 747 p...,neg,10000_4.txt
25002,train,This film lacked something I couldn't put my f...,neg,10001_4.txt
25003,train,"Sorry everyone,,, I know this is supposed to b...",neg,10002_1.txt
25004,train,When I was little my parents took me along to ...,neg,10003_1.txt
25005,train,"""It appears that many critics find the idea of...",neg,10004_3.txt
25006,train,The second attempt by a New York intellectual ...,neg,10005_3.txt
25007,train,"I don't know who to blame, the timid writers o...",neg,10006_4.txt
25008,train,This film is mediocre at best. Angie Harmon is...,neg,10007_1.txt
25009,train,The film is bad. There is no other way to say ...,neg,10008_2.txt
25010,train,This film is one giant pant load. Paul Schrade...,neg,10009_1.txt
25011,train,"The plot for Descent, if it actually can be ca...",neg,1000_4.txt
25012,train,Plot is not worth discussion even if it hints ...,neg,10010_3.txt
25013,train,This film is about a male escort getting invol...,neg,10011_3.txt
25014,train,This movie must be in line for the most boring...,neg,10012_1.txt
25015,train,A worn-out plot of a man who takes the rap for...,neg,10013_1.txt
25016,train,I saw this movie at a drive-in in 1959. Until ...,neg,10014_2.txt
25017,train,Ghost of Dragstrip Hollow is a typical 1950's ...,neg,10015_2.txt
25018,train,"""Ghost of Dragstrip Hollow"" was one of the man...",neg,10016_4.txt
25019,train,"""Ghost of Dragstrip Hollow"" appears to take pl...",neg,10017_4.txt
25020,train,The characters are unlikeable and the script i...,neg,10018_3.txt
25021,train,Kareena Kapoor in a bikini hmmmmmmmm.<br /><br...,neg,10019_3.txt
25022,train,I rented this on DVD and I kind of feel bad si...,neg,1001_4.txt
25023,train,Vijay Krishna Acharya's 'Tashan' is a over-hyp...,neg,10020_3.txt
25024,train,The worst movie I have seen since Tera Jadoo C...,neg,10021_2.txt
25025,train,Summer season is here when the choices in the ...,neg,10022_4.txt
25026,train,Shame on Yash Raj films and Aditya Chopra who ...,neg,10023_1.txt
25027,train,First lesson that some film makers (particular...,neg,10024_3.txt
25028,train,If this is a 2008 product from one of the bigg...,neg,10025_1.txt
25029,train,"I had some expectation for the movie, since it...",neg,10026_2.txt
...,...,...,...,...
99970,train,This is without a doubt the worst movie I have...,unsup,9975_0.txt
99971,train,Note: I've only seen the MST version of this f...,unsup,9976_0.txt
99972,train,I've seen the MST3K version of this movie unde...,unsup,9977_0.txt
99973,train,This disillusioning tale of time travel is mor...,unsup,9978_0.txt
99974,train,"All right, enough with the MST3K-ing, people. ...",unsup,9979_0.txt
99975,train,I saw this in Pittsburgh PA in a small theater...,unsup,997_0.txt
99976,train,And then filmed during each actors day off at ...,unsup,9980_0.txt
99977,train,"Hey, it's not a time machine, it's a ""time tra...",unsup,9981_0.txt
99978,train,"This backyard movie has it all: time travel, a...",unsup,9982_0.txt
99979,train,"It was a true labor to sit through this ""movie...",unsup,9983_0.txt
99980,train,The comments already posted for this film do n...,unsup,9984_0.txt
99981,train,One of the funnier MST3K experiments. This was...,unsup,9985_0.txt
99982,train,Time Chasers is probably one of the better mov...,unsup,9986_0.txt
99983,train,... to dull the incredible pain this stinkmast...,unsup,9987_0.txt
99984,train,I feel badly for the actors and directors of t...,unsup,9988_0.txt
99985,train,I'm not really sure they were trying to make a...,unsup,9989_0.txt
99986,train,I got a screener of this film a couple of week...,unsup,998_0.txt
99987,train,****SPOILERS****SPOILERS****SPOILERS****SPOILE...,unsup,9990_0.txt
99988,train,"This is a really dumb movie, with a very low b...",unsup,9991_0.txt
99989,train,Nick Miller has developed a means of time trav...,unsup,9992_0.txt
99990,train,That's what the director of this film had to b...,unsup,9993_0.txt
99991,train,Think of this one as Back to the Future...exce...,unsup,9994_0.txt
99992,train,What happened to the 'second' hero who went ba...,unsup,9995_0.txt
99993,train,Tangents (better known to MST3K watchers as Ti...,unsup,9996_0.txt
99994,train,Time Chasers joins various films that have bee...,unsup,9997_0.txt
99995,train,"Delightfully awful! Made by David Giancola, a ...",unsup,9998_0.txt
99996,train,"Watching Time Chasers, it obvious that it was ...",unsup,9999_0.txt
99997,train,At the beginning we can see members of Troma t...,unsup,999_0.txt
99998,train,"The movie was incredible, ever since I saw it ...",unsup,99_0.txt
99999,train,"TCM came through by acquiring this wonderful, ...",unsup,9_0.txt

In [11]:
imdb[imdb['label'] != 'unsup']

,type,review,label,file
0,test,Once again Mr. Costner has dragged out a movie...,neg,0_2.txt
1,test,This is an example of why the majority of acti...,neg,10000_4.txt
2,test,"First of all I hate those moronic rappers, who...",neg,10001_1.txt
3,test,Not even the Beatles could write songs everyon...,neg,10002_3.txt
4,test,Brass pictures (movies is not a fitting word f...,neg,10003_3.txt
5,test,"A funny thing happened to me while watching ""M...",neg,10004_2.txt
6,test,This German horror film has to be one of the w...,neg,10005_2.txt
7,test,"Being a long-time fan of Japanese film, I expe...",neg,10006_2.txt
8,test,"""Tokyo Eyes"" tells of a 17 year old Japanese g...",neg,10007_4.txt
9,test,Wealthy horse ranchers in Buenos Aires have a ...,neg,10008_4.txt
10,test,Cage plays a drunk and gets high critically pr...,neg,10009_3.txt
11,test,"First of all, I would like to say that I am a ...",neg,1000_3.txt
12,test,So tell me - what serious boozer drinks Budwei...,neg,10010_2.txt
13,test,A big disappointment for what was touted as an...,neg,10011_1.txt
14,test,This film is absolutely appalling and awful. I...,neg,10012_1.txt
15,test,Here's a decidedly average Italian post apocal...,neg,10013_4.txt
16,test,At the bottom end of the apocalypse movie scal...,neg,10014_2.txt
17,test,Earth has been destroyed in a nuclear holocaus...,neg,10015_4.txt
18,test,Many people are standing in front of the house...,neg,10016_3.txt
19,test,New York family is the last in their neighborh...,neg,10017_1.txt
20,test,"The best thing about ""The Prey"" is the tag lin...",neg,10018_1.txt
21,test,"This is truly, without exaggerating, one of th...",neg,10019_1.txt
22,test,I'm a huge fan of both Emily Watson (Breaking ...,neg,1001_4.txt
23,test,"Sure, most of the slasher films of the 1980's ...",neg,10020_1.txt
24,test,I think that would have been a more appropriat...,neg,10021_3.txt
25,test,1980 was certainly a year for bad backwoods sl...,neg,10022_4.txt
26,test,Everything everyone has said already pretty mu...,neg,10023_4.txt
27,test,"Uhhh ... so, did they even have writers for th...",neg,10024_3.txt
28,test,"Oh yeah, this one is definitely a strong conte...",neg,10025_2.txt
29,test,"Supercraptastic slasher fare, which feels over...",neg,10026_3.txt
...,...,...,...,...
49970,train,"its not as good as the first movie,but its a g...",pos,9975_10.txt
49971,train,"Sure, it was cheesy and nonsensical and at tim...",pos,9976_7.txt
49972,train,SPOILERS THROUGH: <br /><br />I really am in t...,pos,9977_7.txt
49973,train,"I have to say, I loved Vanishing Point. I've s...",pos,9978_8.txt
49974,train,"To start off with, since this movie is a remak...",pos,9979_7.txt
49975,train,I have to agree with most of the other posts. ...,pos,997_7.txt
49976,train,Any movie that shows federal PIGs (Persons In ...,pos,9980_8.txt
49977,train,In Canadian director Kari Skogland's film adap...,pos,9981_7.txt
49978,train,I saw this movie last night after waiting ages...,pos,9982_9.txt
49979,train,"This movie is about basically human relations,...",pos,9983_7.txt
49980,train,I was surprised at just how much I enjoyed thi...,pos,9984_9.txt
49981,train,I saw this film in Winnipeg recently - appropr...,pos,9985_9.txt
49982,train,As perhaps one of the few Canadians who did no...,pos,9986_9.txt
49983,train,I was very moved by the story and because I am...,pos,9987_9.txt
49984,train,What I loved about the on-screen adaptation of...,pos,9988_8.txt
49985,train,I had a chance to see a screening of this movi...,pos,9989_9.txt
49986,train,This is a really interesting movie. It is an a...,pos,998_7.txt
49987,train,I saw the movie recently and really liked it. ...,pos,9990_8.txt
49988,train,I thought this movie was hysterical. I have wa...,pos,9991_10.txt
49989,train,...this is a classic with so many great dialog...,pos,9992_10.txt
49990,train,The most hillarious and funny Brooks movie I e...,pos,9993_10.txt
49991,train,"""Life stinks"" is a parody of life and death, h...",pos,9994_10.txt
49992,train,This is the kind of film you want to see with ...,pos,9995_10.txt
49993,train,I have not read the other comments on the film...,pos,9996_9.txt
49994,train,Life Stinks (1991) was a step below Mel Brooks...,pos,9997_7.txt
49995,train,"Seeing as the vote average was pretty low, and...",pos,9998_9.txt
49996,train,"The plot had some wretched, unbelievable twist...",pos,9999_8.txt
49997,train,I am amazed at how this movie(and most others ...,pos,999_10.txt
49998,train,A Christmas Together actually came before my t...,pos,99_8.txt
49999,train,Working-class romantic drama from director Mar...,pos,9_7.txt

In [12]:
train = imdb[(imdb['type'] ==  'train') & (imdb['label'] != 'unsup')]

In [13]:
len(train)

25000

In [14]:
from sklearn import metrics

In [15]:
from sklearn.feature_extraction import stop_words
 
print(stop_words.ENGLISH_STOP_WORDS)

frozenset({'thence', 'hereby', 'serious', 'name', 'amoungst', 'thereupon', 'becomes', 'detail', 'ltd', 'elsewhere', 'throughout', 'yourself', 'beforehand', 'its', 'mill', 'such', 'anything', 'same', 'others', 'me', 'nevertheless', 'into', 'rather', 'sixty', 'without', 'empty', 'everywhere', 'whereafter', 'moreover', 'back', 'former', 'his', 'are', 'how', 'thru', 'at', 'herself', 'could', 'per', 'call', 'everything', 'off', 'forty', 'four', 'whom', 'many', 'there', 'enough', 'fifty', 'full', 'less', 'un', 'yourselves', 'seem', 'something', 'them', 'sometime', 'top', 'alone', 'being', 'below', 'found', 'noone', 'whoever', 'fire', 'next', 'hundred', 'than', 'seems', 'not', 'otherwise', 'besides', 'thin', 'was', 'about', 'last', 'put', 'some', 'itself', 'someone', 'namely', 'these', 'she', 're', 'still', 'amount', 'couldnt', 'although', 'from', 'therein', 'this', 'through', 'more', 'you', 'with', 'though', 'but', 'move', 'cant', 'since', 'no', 'only', 'either', 'if', 'three', 'fill', 'whereby', 'against', 'before', 'get', 'too', 'of', 'we', 'can', 'herein', 'i', 'neither', 'afterwards', 'where', 'latter', 'whether', 'most', 'somehow', 'himself', 'nine', 'twenty', 'until', 'down', 'every', 'seeming', 'up', 'else', 'who', 'their', 'then', 'were', 'whither', 'yet', 'whence', 'during', 'go', 'co', 'had', 'much', 'thus', 'for', 'to', 'toward', 'well', 'however', 'be', 'few', 'twelve', 'done', 'around', 'myself', 'any', 'which', 'eight', 'been', 'has', 'often', 'meanwhile', 'cry', 'mostly', 'sometimes', 'never', 'a', 'as', 'two', 'the', 'etc', 'because', 'on', 'ie', 'it', 'those', 'except', 'once', 'always', 'eg', 'here', 'six', 'describe', 'together', 'ourselves', 'see', 'why', 'so', 'between', 'when', 'hers', 'via', 'made', 'while', 'am', 'again', 'and', 'least', 'themselves', 'anyway', 'whatever', 'other', 'third', 'an', 'even', 'us', 'whole', 'might', 'along', 'must', 'nowhere', 'very', 'may', 'none', 'one', 'hereafter', 'yours', 'part', 'that', 'under', 'her', 'amongst', 'over', 'somewhere', 'several', 'ours', 'please', 'is', 'find', 'have', 'also', 'another', 'already', 'mine', 'further', 'hasnt', 'nothing', 'within', 'onto', 'wherein', 'what', 'do', 'should', 'hence', 'system', 'by', 'thereafter', 'all', 'first', 'ten', 'ever', 'both', 'out', 'would', 'or', 'seemed', 'cannot', 'our', 'latterly', 'each', 'become', 'bottom', 'beyond', 'your', 'due', 'perhaps', 'hereupon', 'de', 'front', 'anyone', 'in', 'take', 'towards', 'eleven', 'inc', 'nor', 'whenever', 'nobody', 'they', 'my', 'became', 'everyone', 'among', 'show', 'whose', 'anywhere', 'sincere', 'now', 'thick', 'above', 'becoming', 'bill', 'five', 'wherever', 'him', 'indeed', 'con', 'own', 'give', 'across', 'keep', 'fifteen', 'almost', 'interest', 'side', 'upon', 'thereby', 'whereupon', 'behind', 'he', 'whereas', 'after', 'therefore', 'will', 'anyhow', 'beside', 'formerly'})

In [16]:
cv = CountVectorizer(stop_words = 'english')

In [17]:
bow = cv.fit(train['review'])

In [18]:
bow_transform =bow.transform(train['review'])

In [27]:
classifier_mnb = MultinomialNB().fit(bow_transform, train['label'])

In [28]:
test = imdb[(imdb['type'] == 'test') & (imdb['label'] != 'unsup')]

In [29]:
bow_comments = bow.transform(test['review'])

In [30]:
from sklearn import metrics

In [31]:
predictions = classifier_mnb.predict(bow_comments)

In [32]:
metrics.accuracy_score(test['label'], predictions)

0.8196

In [33]:
# naive bayes - 0.803
# naive bayes + stopwords - 0.8196

In [34]:
predictions

array(['neg', 'neg', 'neg', ..., 'pos', 'pos', 'pos'],
      dtype='<U3')

In [35]:
test['label']

0        neg
1        neg
2        neg
3        neg
4        neg
5        neg
6        neg
7        neg
8        neg
9        neg
10       neg
11       neg
12       neg
13       neg
14       neg
15       neg
16       neg
17       neg
18       neg
19       neg
20       neg
21       neg
22       neg
23       neg
24       neg
25       neg
26       neg
27       neg
28       neg
29       neg
        ...
24970    pos
24971    pos
24972    pos
24973    pos
24974    pos
24975    pos
24976    pos
24977    pos
24978    pos
24979    pos
24980    pos
24981    pos
24982    pos
24983    pos
24984    pos
24985    pos
24986    pos
24987    pos
24988    pos
24989    pos
24990    pos
24991    pos
24992    pos
24993    pos
24994    pos
24995    pos
24996    pos
24997    pos
24998    pos
24999    pos
Name: label, Length: 25000, dtype: object

In [37]:
bow_test = bow.transform (['''The eye-popping visual effects, are the highlight of this tale of a theme park gone mad. The public's endless fascination with dinosaurs made this a top money-maker; but aside from it's visual effects, the film is a seemingly endless yawn-fest. Character development is so basic, that, except for their ages, you'd have a hard time telling the kids from the adults. Everyone, except the dinosaurs are void of personality. When the creatures aren't on the screen, you're subjected to a screenplay that features dull, one-dimensional characters spouting boring dialog. Steven Spielberg seems to have lost his ability to direct a film, that grips an audience with its storytelling (Duel, Jaws, Close Encounters). If you want to see a film with a good story, great characters and interesting dialog, stay away from "Jurassic Park". If special effects are your thing, then by all means, watch and enjoy.'''])
test_prediction = classifier_mnb.predict(bow_test)
print(test_prediction)
print(round(classifier_mnb.predict_proba(bow_test)[0][1], 5))

['neg']
0.0

In [38]:
# webscrapping

In [39]:
from urllib.request import Request, urlopen as uReq
from bs4 import BeautifulSoup as soup
import pandas as pd

In [40]:
def make_soup(website):
    
    req = Request(website, headers= {'User-Agent' : 'Mozilla/5.0'}) 
    uClient = uReq(req)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    return page_soup

In [41]:
GOOGLE_NEWS_URL = 'https://www.google.com.my/search?q={}&source=lnt&tbm=nws'

def forge_url(q):
    return GOOGLE_NEWS_URL.format(q.replace(' ','+'))

In [42]:
news_url = forge_url('avengers')

In [43]:
website = make_soup(news_url)

In [44]:
website.h3

<h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/30/avengers-4-scarlet-witch-elizabeth-olsen-code-name/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIFCgAMAA&amp;usg=AOvVaw2a0nNp_FiSZr_nFT_PA_Qk"><b>Avengers</b>' Scarlet Witch Has Yet to Be Called by Her Code Name</a></h3>

In [45]:
website.findAll('h3')

[<h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/30/avengers-4-scarlet-witch-elizabeth-olsen-code-name/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIFCgAMAA&amp;usg=AOvVaw2a0nNp_FiSZr_nFT_PA_Qk"><b>Avengers</b>' Scarlet Witch Has Yet to Be Called by Her Code Name</a></h3>,
 <h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/29/avengers-infinity-war-mind-stone-villain-theory-thanos/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIFygAMAE&amp;usg=AOvVaw0Viu8Q8q-FmPTfJXIyzWCQ">'<b>Avengers</b>: Infinity War' Fan Theory Reveals the True Villain of the Film</a></h3>,
 <h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/30/avengers-infinity-war-thanos-gauntlet-sipper-returns-disneyland-resort/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIICgAMAI&amp;usg=AOvVaw2J9onZzBgw96GaoznAAoZ3">Sold Out '<b>Avengers</b>: Infinity War' Gauntlet Sipper Returns to ...</a></h3>,
 <h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/29/marvel-avengers-loki-design-casual-wear/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIIygAMAM&amp;usg=AOvVaw3iyliUMDvQlpA5MAcRnXxb">'<b>Avengers</b>': Loki's Casual Wear Designs Revealed</a></h3>,
 <h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/30/avengers-4-gwyneth-paltrow-marries-brad-falchuk-american-horror-story/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIJigAMAQ&amp;usg=AOvVaw2aWhqTfrrx8HDu2_Jm_5If">'<b>Avengers</b> 4' Star Gwyneth Paltrow Weds 'American Horror Story' Co ...</a></h3>,
 <h3 class="r"><a href="/url?q=https://comicbook.com/marvel/2018/09/28/avengers-4-gwyneth-paltrow-marries-brad-falchuk-american-horror-story/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIKygAMAU&amp;usg=AOvVaw0_HgkyOtwR5_KCaZ3yBM6n">'<b>Avengers</b>: Infinity War' Star Gwyneth Paltrow Is Getting Married This ...</a></h3>,
 <h3 class="r"><a href="/url?q=https://www.mydaytondailynews.com/entertainment/avengers-actor-anthony-mackie-holds-own-against-atlanta-falcons-fan/8rCVadPHsgmpA19AqHaiNM/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIILigAMAY&amp;usg=AOvVaw02SoUuHLZpfWwot15a98sE">'<b>Avengers</b>' actor Anthony Mackie holds own against Atlanta Falcons ...</a></h3>,
 <h3 class="r"><a href="/url?q=https://www.express.co.uk/entertainment/films/1024167/Avengers-4-theory-Soul-Stone-Heimdall-Infinity-War&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIMSgAMAc&amp;usg=AOvVaw0r19NZ-rxAK4lkp6AHxc83"><b>Avengers</b> 4: Mind-blowing theory links THIS character to the Soul ...</a></h3>,
 <h3 class="r"><a href="/url?q=http://mentalfloss.com/article/558862/avengers-4-fan-theory-adds-x-men-fantastic-four-mcu&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIINCgAMAg&amp;usg=AOvVaw2USX0tXSDPrtzeE81tp90g"><b>Avengers</b> 4 Theory Explains How to Include X-Men and Fantastic Four</a></h3>,
 <h3 class="r"><a href="/url?q=https://www.express.co.uk/entertainment/films/1023089/Avengers-4-concept-art-leak-Captain-Marvel-Iron-Man-Thanos-Captain-America-Ronin-Thor&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIOigAMAk&amp;usg=AOvVaw0tmCBrRI_6VvV0mvJ4_cST"><b>Avengers</b> 4 concept art LEAK: New look at Captain Marvel, Iron Man ...</a></h3>]

In [46]:
website.h3.a

<a href="/url?q=https://comicbook.com/marvel/2018/09/30/avengers-4-scarlet-witch-elizabeth-olsen-code-name/&amp;sa=U&amp;ved=0ahUKEwiUo6HSreLdAhXJO48KHQaPDLAQqQIIFCgAMAA&amp;usg=AOvVaw2a0nNp_FiSZr_nFT_PA_Qk"><b>Avengers</b>' Scarlet Witch Has Yet to Be Called by Her Code Name</a>

In [47]:
website.h3.a.text

"Avengers' Scarlet Witch Has Yet to Be Called by Her Code Name"

In [48]:
news_headlines = pd.DataFrame(columns = ['title', 'sentiment', 'score'])

In [49]:
news_headlines

Empty DataFrame
Columns: [title, sentiment, score]
Index: []

In [50]:
headlines = website.findAll("h3")

In [51]:

n = 0
for item in headlines: 
    top = item.a
    text_headlines = top.text
    print(text_headlines)
    n += 1
    news_headlines.loc[n-1, 'title'] = text_headlines

Avengers' Scarlet Witch Has Yet to Be Called by Her Code Name
'Avengers: Infinity War' Fan Theory Reveals the True Villain of the Film
Sold Out 'Avengers: Infinity War' Gauntlet Sipper Returns to ...
'Avengers': Loki's Casual Wear Designs Revealed
'Avengers 4' Star Gwyneth Paltrow Weds 'American Horror Story' Co ...
'Avengers: Infinity War' Star Gwyneth Paltrow Is Getting Married This ...
'Avengers' actor Anthony Mackie holds own against Atlanta Falcons ...
Avengers 4: Mind-blowing theory links THIS character to the Soul ...
Avengers 4 Theory Explains How to Include X-Men and Fantastic Four
Avengers 4 concept art LEAK: New look at Captain Marvel, Iron Man ...

In [52]:
news_headlines.head()

                                               title sentiment score
0  Avengers' Scarlet Witch Has Yet to Be Called b...       NaN   NaN
1  'Avengers: Infinity War' Fan Theory Reveals th...       NaN   NaN
2  Sold Out 'Avengers: Infinity War' Gauntlet Sip...       NaN   NaN
3    'Avengers': Loki's Casual Wear Designs Revealed       NaN   NaN
4  'Avengers 4' Star Gwyneth Paltrow Weds 'Americ...       NaN   NaN

In [54]:
news_headlines.head()

                                               title sentiment score
0  Avengers' Scarlet Witch Has Yet to Be Called b...       NaN   NaN
1  'Avengers: Infinity War' Fan Theory Reveals th...       NaN   NaN
2  Sold Out 'Avengers: Infinity War' Gauntlet Sip...       NaN   NaN
3    'Avengers': Loki's Casual Wear Designs Revealed       NaN   NaN
4  'Avengers 4' Star Gwyneth Paltrow Weds 'Americ...       NaN   NaN

In [55]:
n = 0 
for i in news_headlines['title']:
    print(i)
    n += 1
    bow_comments = bow.transform([i])
    predictions = classifier_mnb.predict(bow_comments)
    score = round(classifier_mnb.predict_proba(bow_comments)[0][1],5)
    news_headlines.loc[n-1,'sentiment'] = predictions
    news_headlines.loc[n-1, 'score'] = score
    print(predictions)
    print(score)

Avengers' Scarlet Witch Has Yet to Be Called by Her Code Name
['neg']
0.25957
'Avengers: Infinity War' Fan Theory Reveals the True Villain of the Film
['pos']
0.53084
Sold Out 'Avengers: Infinity War' Gauntlet Sipper Returns to ...
['pos']
0.60519
'Avengers': Loki's Casual Wear Designs Revealed
['neg']
0.2037
'Avengers 4' Star Gwyneth Paltrow Weds 'American Horror Story' Co ...
['neg']
0.42855
'Avengers: Infinity War' Star Gwyneth Paltrow Is Getting Married This ...
['neg']
0.4198
'Avengers' actor Anthony Mackie holds own against Atlanta Falcons ...
['pos']
0.85139
Avengers 4: Mind-blowing theory links THIS character to the Soul ...
['neg']
0.22827
Avengers 4 Theory Explains How to Include X-Men and Fantastic Four
['pos']
0.53465
Avengers 4 concept art LEAK: New look at Captain Marvel, Iron Man ...
['neg']
0.29621

In [56]:
news_headlines

                                               title sentiment    score
0  Avengers' Scarlet Witch Has Yet to Be Called b...     [neg]  0.25957
1  'Avengers: Infinity War' Fan Theory Reveals th...     [pos]  0.53084
2  Sold Out 'Avengers: Infinity War' Gauntlet Sip...     [pos]  0.60519
3    'Avengers': Loki's Casual Wear Designs Revealed     [neg]   0.2037
4  'Avengers 4' Star Gwyneth Paltrow Weds 'Americ...     [neg]  0.42855
5  'Avengers: Infinity War' Star Gwyneth Paltrow ...     [neg]   0.4198
6  'Avengers' actor Anthony Mackie holds own agai...     [pos]  0.85139
7  Avengers 4: Mind-blowing theory links THIS cha...     [neg]  0.22827
8  Avengers 4 Theory Explains How to Include X-Me...     [pos]  0.53465
9  Avengers 4 concept art LEAK: New look at Capta...     [neg]  0.29621

In [95]:
news_headlines.to_csv('news_sentiment.csv', encoding = 'utf-8', index= False)